### ISSUE TITLE
The size of the videos is larger than the capacity of the colab

### ISSUE THREAD

**Issue by mh-y** [rajanjitenpatel/C3D_feature_extraction#13]
How do you extract features at once when the video is larger than the capacity of the colab?

**Comment by rutviz** [comment]
You can upload the video to google drive and you can access google drive
through colab.
I hope I understood what you are looking for.

**Comment by mh-y** [comment]
I bought 100GB of capacity from Google Drive and was able to extract features. Thank you for your help.
