### ISSUE TITLE
About video with total frames less than 32*16

### ISSUE THREAD

**Issue by linshuheng6** [rajanjitenpatel/C3D_feature_extraction#2]
Hi, thank you for your pre-extracted features of dataset UCF-crime. I have a question that why do those video with frames less than 32(the number of segments in a video) * 16 (FPS)，namely ，some short-time video, not exist in your pre-extracted features?

Looking forward to your reply!
Thank you!

**Comment by fjchange** [comment]
You can comment the code `if  num_frames<512: ....`
And a palce you should change because of difference between matlab and python,
`thirty2_shots=np.round(np.linspace(0,len(data)-1,num=33))`

**Comment by linshuheng6** [comment]
@fjchange  Thanks, the problem is solved!
