### ISSUE TITLE
Hdf5 directory not found

### ISSUE THREAD

**Issue by suyash8991** [rajanjitenpatel/C3D_feature_extraction#4]
I compiled the code using 
!sudo make all
I am getting the error of hdf5.
`
protoc --proto_path=src --cpp_out=build/src src/caffe/proto/caffe.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: caffe/proto/caffe.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)

protoc --proto_path=src --cpp_out=build/src src/caffe/proto/caffe_pretty_print.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: caffe/proto/caffe_pretty_print.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: caffe/proto/caffe.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)

/usr/bin/g++ build/src/caffe/proto/caffe.pb.cc -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -c -o build/src/caffe/proto/caffe.pb.o

/usr/bin/g++ build/src/caffe/proto/caffe_pretty_print.pb.cc -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -c -o build/src/caffe/proto/caffe_pretty_print.pb.o

/usr/bin/g++ src/caffe/layer_factory.cpp -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -c -o build/src/caffe/layer_factory.o
In file included from ./include/caffe/vision_layers.hpp:13:0,
                 from src/caffe/layer_factory.cpp:9:
./include/caffe/neuron_layers.hpp:13:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
Makefile:360: recipe for target 'build/src/caffe/layer_factory.o' failed
make: *** [build/src/caffe/layer_factory.o] Error 1 `

**Comment by rajanjitenpatel** [comment]
Install following dependency
```
!sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libboost-all-dev libhdf5-serial-dev
```

Clear and compile code again.
```
!sudo make clean
!sudo make all
```

I hope this will clear your issue.

**Comment by suyash8991** [comment]
Thank you Sir but after that I am getting no kernel image error.
I am getting another error while running the code
# extract feature
%cd /content/C3D/C3D-v1.0/examples/c3d_feature_extraction
!sudo bash c3d_sport1m_feature_extraction_frm.sh


ERROR

F0123 16:46:06.593704  4321 vol2col.cu:75] Check failed: error == cudaSuccess (48 vs. 0)  no kernel image is available for execution on the device
*** Check failure stack trace: ***
c3d_sport1m_feature_extraction_frm.sh: line 7:  4321 Aborted                 (core dumped) GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin prototxt/c3d_sport1m_feature_extractor_frm.prototxt conv3d_deepnetA_sport1m_iter_1900000 0 50 1 prototxt/output_list_prefix.txt fc7-1 fc6-1 prob
