### ISSUE TITLE
looking for .fc files

### ISSUE THREAD

**Issue by cervantes-loves-ai** [rajanjitenpatel/C3D_feature_extraction#6]
you've uploaded all extracted features of ucf crime dataset thanks a lot for that

do you have .fc files also? will be great if you share.

**Comment by rajanjitenpatel** [comment]
I don't have .fc file. But you can generate it using simple following python command to list all file path in "out" dir. for now.
```
from os import listdir
from os.path import isfile, join
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
```
I will try to generate it and share it soon.
