### ISSUE TITLE
Check failed: error == cudaSuccess (38 vs. 0)  no CUDA-capable device is detected

### ISSUE THREAD

**Issue by Ol0fmeistR** [rajanjitenpatel/C3D_feature_extraction#7]
Hi @rajanjitenpatel 
First of all, thank you for your extracted feature files. While I was trying to extract features by running the extract_C3D_feature.py I was encountering this error:
![Screenshot (150)](https://user-images.githubusercontent.com/33911770/67800192-e1bba200-faac-11e9-8611-addba1c5483f.png)
Upon doing a google search most of it revolved around the system not having a GPU but in my case, the GPU surely was getting detected.
![Screenshot (179)](https://user-images.githubusercontent.com/33911770/67800730-cdc47000-faad-11e9-8a5f-56246605e8f2.png)
Not really sure if it's something related to the caffe build or not. Any sort of workaround for the problem would be much appreciated.

**Comment by rajanjitenpatel** [comment]
Hi Arindam,

Before running code on notebook, please make sure your GPU is enable on
Google CoLab.

To check gpu is enable just hover on "RAM & DISK".

To enable GPU.
From "runtime" dropdown menu on top.

https://images.app.goo.gl/geJhMWL4qn5irM2m9

Thanks,
Rajan Patel,
www.rjprime.info

**Comment by Ol0fmeistR** [comment]
Enabling GPU was the very first thing I did, even before executing a single line of code. Even restarted the runtime instances with GPU enabled twice just to make sure that GPU was enabled; still getting this error. ☹

**Comment by Ol0fmeistR** [comment]
However, when testing out the feature extraction process on the sample images it does detect the GPU(GPU:0) and successfully extracts 16 features for 1 batch.
![Screenshot (213)](https://user-images.githubusercontent.com/33911770/67845961-672f6880-fb26-11e9-8fb9-6dba08c9c33c.png)
![Screenshot (378)](https://user-images.githubusercontent.com/33911770/67846096-a1990580-fb26-11e9-9577-af8b3aebaefa.png)

**Comment by rajanjitenpatel** [comment]
Can u share pdf of executed notebook? It will be more convenient to debug.

**Comment by Ol0fmeistR** [comment]
Sure thing, attached below is the pdf of the executed notebook.
[feature_extraction.pdf](https://github.com/rajanjitenpatel/C3D_feature_extraction/files/3800259/feature_extraction.pdf)

**Comment by rajanjitenpatel** [comment]
Can you replace your extract_C3D_feature.py with following file and try to run it again https://github.com/rajanjitenpatel/C3D_feature_extraction/blob/master/extract_C3D_feature.py

For me it is working without any error. 

[C3D.pdf](https://github.com/rajanjitenpatel/C3D_feature_extraction/files/3917850/C3D.pdf)
