### ISSUE TITLE
#failed to read chunk list 

### ISSUE THREAD

**Issue by rihemmhd** [rajanjitenpatel/C3D_feature_extraction#9]
Hi @rajanjitenpatel,

Thanks for your C3D features .
but While I was trying to extract examples features by running  extract_C3D_feature.py I was encountering this error:

[Info] trained_model=/content/drive/My Drive/C3D/C3D-v1.0/examples/c3d_feature_extraction/conv3d_deepnetA_sport1m_iter_1900000 found. Good to go!
width = 320.0
height = 240.0
[Info] num_frames=164, fps=25.0
[Info] Running C3D feature extraction: "/content/drive/My Drive/C3D/C3D-v1.0/build/tools/extract_image_features.bin /content/drive/My Drive/C3D/C3D-v1.0/examples/c3d_feature_extraction/output/feature_extraction.prototxt /content/drive/My Drive/C3D/C3D-v1.0/examples/c3d_feature_extraction/conv3d_deepnetA_sport1m_iter_1900000 0 50 9999999 /content/drive/My Drive/C3D/C3D-v1.0/examples/c3d_feature_extraction/output/output_prefix.txt fc6-1"
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1223 10:41:02.835363  3116 extract_image_features.cpp:64] Using GPU #0
I1223 10:41:02.837381  3116 net.cpp:76] Creating Layer data
I1223 10:41:02.837402  3116 net.cpp:112] data -> data
I1223 10:41:02.837447  3116 net.cpp:112] data -> label
I1223 10:41:02.837568  3116 video_data_layer.cpp:283] Opening file /content/drive/My Drive/C3D/C3D-v1.0/examples/c3d_feature_extraction/input/avi/v_ApplyEyeMakeup_g01_c01.avi
I1223 10:41:02.838238  3116 video_data_layer.cpp:308] **failed to read chunk list**
I1223 10:41:02.838255  3116 video_data_layer.cpp:317] ****A total of 0 video chunks****.
[Error] feature extraction failed!

**Comment by iShahadH** [comment]
Hi, I would like to ask you how did you solved this problem??

Thanks
